/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersNewRouteImport } from './routes/suppliers.new'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as DefectsNewRouteImport } from './routes/defects.new'
import { Route as DefectsIdRouteImport } from './routes/defects.$id'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersNewRoute = SuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DefectsNewRoute = DefectsNewRouteImport.update({
  id: '/defects/new',
  path: '/defects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DefectsIdRoute = DefectsIdRouteImport.update({
  id: '/defects/$id',
  path: '/defects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/defects/$id': typeof DefectsIdRoute
  '/defects/new': typeof DefectsNewRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/suppliers/new': typeof SuppliersNewRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/defects/$id': typeof DefectsIdRoute
  '/defects/new': typeof DefectsNewRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/suppliers/new': typeof SuppliersNewRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/defects/$id': typeof DefectsIdRoute
  '/defects/new': typeof DefectsNewRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/suppliers/new': typeof SuppliersNewRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/defects/$id'
    | '/defects/new'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports'
    | '/defects/$id'
    | '/defects/new'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/reports'
    | '/defects/$id'
    | '/defects/new'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsRoute: typeof ReportsRoute
  DefectsIdRoute: typeof DefectsIdRoute
  DefectsNewRoute: typeof DefectsNewRoute
  SuppliersIdRoute: typeof SuppliersIdRoute
  SuppliersNewRoute: typeof SuppliersNewRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/new': {
      id: '/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof SuppliersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defects/new': {
      id: '/defects/new'
      path: '/defects/new'
      fullPath: '/defects/new'
      preLoaderRoute: typeof DefectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defects/$id': {
      id: '/defects/$id'
      path: '/defects/$id'
      fullPath: '/defects/$id'
      preLoaderRoute: typeof DefectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsRoute: ReportsRoute,
  DefectsIdRoute: DefectsIdRoute,
  DefectsNewRoute: DefectsNewRoute,
  SuppliersIdRoute: SuppliersIdRoute,
  SuppliersNewRoute: SuppliersNewRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
